### ISSUE TITLE
how this?

### ISSUE THREAD

**Issue by yntkts555** [v1s1t0r999/LocateMe#5]
**Name the issue as:** _OptionNumber: Error_ Eg:[`Option#2: Unexpected Error Occurred`]

**ErrorLog.log's Content: **
_[DATE@TIME]: ERROR_

**Where did it take place?**
2. Then '....'
3. Shows '....'
4. Error happens

"Running Firefox as root in a regular user's session is not supported"

**What did you expect?**
A clear and concise description of what you think should've happened

**Images (preferably Screenshots):**
If possible, add images to help explain your problem. PNG format is good to be attached.

**Operating System (Required):**
 - OS: [Eg: `mx linux`]
 - OS Version: [Eg: ``]
 - LocateMe Version: [Eg: `v1.0.0`]

**Other Info**

**Comment by v1s1t0r999** [comment]
Check the update.

**Comment by v1s1t0r999** [comment]
Closing @yntkts555
